version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    # environment:
    #   - MONGO_URI=mongodb+srv://mayank:${password}@cluster0.dxf2y.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
  #   depends_on:
  #     - mongo
  # mongo:
  #   image: mongo:latest
  #   ports:
  #     - "27017:27017"
